-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.detalle_pedidos
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    pedido_id uuid,
    producto_id uuid,
    CONSTRAINT detalle_pedidos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prc_banner_superior
(
    id integer NOT NULL DEFAULT nextval('prc_banner_superior_id_seq'::regclass),
    id_imagen integer,
    link character varying(255) COLLATE pg_catalog."default",
    idestado integer,
    CONSTRAINT prc_banner_superior_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prc_ofertas
(
    id integer NOT NULL DEFAULT nextval('prc_ofertas_id_seq'::regclass),
    id_producto integer,
    fechayhora_creacion timestamp without time zone,
    fechayhora_desde timestamp without time zone,
    fechayhora_hasta timestamp without time zone,
    valido boolean,
    porcentaje_descuento numeric(5, 2),
    idestado integer,
    CONSTRAINT prc_ofertas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prc_pedidos
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    fecha_pedido timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    estado character varying(50) COLLATE pg_catalog."default" NOT NULL,
    subtotal numeric(10, 2) NOT NULL,
    total numeric(10, 2) NOT NULL,
    idestado boolean NOT NULL,
    user_id bigint,
    CONSTRAINT prc_pedidos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prd_megusta_producto
(
    id integer NOT NULL DEFAULT nextval('prd_megusta_producto_id_seq'::regclass),
    id_producto integer,
    contador integer,
    idestado integer,
    CONSTRAINT prd_megusta_producto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prd_producto_imagenes
(
    id integer NOT NULL DEFAULT nextval('prd_producto_imagenes_id_seq'::regclass),
    id_producto character varying(255) COLLATE pg_catalog."default",
    id_imagen integer,
    valido boolean,
    idestado integer,
    CONSTRAINT prd_producto_imagenes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prd_productos_medidas
(
    id integer NOT NULL DEFAULT nextval('prd_productos_medidas_id_seq'::regclass),
    id_producto integer,
    id_medida integer,
    valido boolean,
    existencia integer,
    idestado integer,
    CONSTRAINT prd_productos_medidas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prd_vistas_producto
(
    id integer NOT NULL DEFAULT nextval('prd_vistas_producto_id_seq'::regclass),
    id_producto integer,
    contador integer,
    idestado integer,
    CONSTRAINT prd_vistas_producto_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prm_categorias_niv1
(
    id integer NOT NULL DEFAULT nextval('prm_categorias_niv1_id_seq'::regclass),
    id_imagen integer,
    descripcion text COLLATE pg_catalog."default",
    idestado integer,
    CONSTRAINT prm_categorias_niv1_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prm_categorias_niv2
(
    id integer NOT NULL DEFAULT nextval('prm_categorias_niv2_id_seq'::regclass),
    id_cat_niv1 integer,
    descripcion text COLLATE pg_catalog."default",
    idestado integer,
    CONSTRAINT prm_categorias_niv2_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prm_categorias_niv3
(
    id integer NOT NULL DEFAULT nextval('prm_categorias_niv3_id_seq'::regclass),
    id_cat_niv2 integer,
    id_producto integer,
    descripcion text COLLATE pg_catalog."default",
    idestado integer,
    CONSTRAINT prm_categorias_niv3_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prm_colores
(
    id integer NOT NULL DEFAULT nextval('prm_colores_id_seq'::regclass),
    descripcion text COLLATE pg_catalog."default",
    valido boolean,
    idestado integer,
    CONSTRAINT prm_colores_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prm_envios
(
    id integer NOT NULL DEFAULT nextval('prm_envios_id_seq'::regclass),
    descripcion text COLLATE pg_catalog."default",
    costo_envio numeric(10, 2),
    valido boolean,
    idestado integer,
    CONSTRAINT prm_envios_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prm_imagenes
(
    id integer NOT NULL DEFAULT nextval('prm_imagenes_id_seq'::regclass),
    binario_img bytea,
    ruta_img character varying(255) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    valido boolean,
    idestado integer,
    nombre_archivo character varying COLLATE pg_catalog."default",
    tipo_mime character varying COLLATE pg_catalog."default",
    "tamaño" integer,
    fecha_subida timestamp without time zone,
    CONSTRAINT prm_imagenes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prm_medidas
(
    id integer NOT NULL DEFAULT nextval('prm_medidas_id_seq'::regclass),
    descripcion text COLLATE pg_catalog."default",
    abreviatura character varying(255) COLLATE pg_catalog."default",
    valido boolean,
    idestado integer,
    CONSTRAINT prm_medidas_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.prm_producto
(
    uu_id uuid NOT NULL,
    codigo_alfa character varying(50) COLLATE pg_catalog."default",
    descripcion character varying(255) COLLATE pg_catalog."default",
    precio numeric(10, 2),
    graba_iva boolean,
    marca character varying(100) COLLATE pg_catalog."default",
    color_1 character varying(50) COLLATE pg_catalog."default",
    color_2 character varying(50) COLLATE pg_catalog."default",
    valido boolean,
    dias_entrega integer,
    id_envio integer,
    id_cat_niv3 integer,
    fecha_creacion date,
    producto_destacado boolean,
    idestado integer,
    CONSTRAINT prm_producto_pkey PRIMARY KEY (uu_id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id integer NOT NULL DEFAULT nextval('usuarios_id_seq'::regclass),
    nombreusuario character varying(50) COLLATE pg_catalog."default" NOT NULL,
    contrasena character varying(255) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(255) COLLATE pg_catalog."default",
    nombre character varying(100) COLLATE pg_catalog."default",
    apellido character varying(100) COLLATE pg_catalog."default",
    direccion character varying(255) COLLATE pg_catalog."default",
    ciudad character varying(100) COLLATE pg_catalog."default",
    pais character varying(100) COLLATE pg_catalog."default",
    codigopostal character varying(20) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    fechacreacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fechaactualizacion timestamp without time zone,
    estaactivo boolean DEFAULT true,
    type character varying(20) COLLATE pg_catalog."default" DEFAULT USER,
    CONSTRAINT usuarios_pkey PRIMARY KEY (id),
    CONSTRAINT usuarios_nombreusuario_key UNIQUE (nombreusuario)
);

CREATE TABLE IF NOT EXISTS public.prm_colores_prm_producto
(
    prm_colores_id integer NOT NULL DEFAULT nextval('prm_colores_id_seq'::regclass),
    prm_producto_color_1 character varying(50) COLLATE pg_catalog."default"
);

CREATE TABLE IF NOT EXISTS public.prm_producto_prc_ofertas
(
    prm_producto_uu_id uuid NOT NULL,
    prc_ofertas_id_producto integer
);

CREATE TABLE IF NOT EXISTS public.prm_envios_prc_pedidos
(
    prm_envios_id integer NOT NULL DEFAULT nextval('prm_envios_id_seq'::regclass),
    prc_pedidos_estado character varying(50) COLLATE pg_catalog."default" NOT NULL
);

ALTER TABLE IF EXISTS public.prc_pedidos
    ADD FOREIGN KEY (id)
    REFERENCES public.detalle_pedidos (pedido_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_categorias_niv1
    ADD FOREIGN KEY (id)
    REFERENCES public.prm_categorias_niv2 (id_cat_niv1) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_categorias_niv2
    ADD FOREIGN KEY (id)
    REFERENCES public.prm_categorias_niv3 (id_cat_niv2) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_imagenes
    ADD FOREIGN KEY (id)
    REFERENCES public.prd_producto_imagenes (id_imagen) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_medidas
    ADD FOREIGN KEY (id)
    REFERENCES public.prd_productos_medidas (id_medida) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_producto
    ADD FOREIGN KEY (uu_id)
    REFERENCES public.detalle_pedidos (producto_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_producto
    ADD FOREIGN KEY (uu_id)
    REFERENCES public.prd_megusta_producto (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_producto
    ADD FOREIGN KEY (uu_id)
    REFERENCES public.prd_producto_imagenes (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_producto
    ADD FOREIGN KEY (uu_id)
    REFERENCES public.prd_productos_medidas (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_producto
    ADD FOREIGN KEY (uu_id)
    REFERENCES public.prd_vistas_producto (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_producto
    ADD FOREIGN KEY (id_cat_niv3)
    REFERENCES public.prm_categorias_niv3 (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_producto
    ADD FOREIGN KEY (uu_id)
    REFERENCES public.prd_productos_medidas (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.usuarios
    ADD FOREIGN KEY (id)
    REFERENCES public.prc_pedidos (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_colores_prm_producto
    ADD FOREIGN KEY (prm_colores_id)
    REFERENCES public.prm_colores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_colores_prm_producto
    ADD FOREIGN KEY (prm_producto_color_1)
    REFERENCES public.prm_producto (color_1) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_producto_prc_ofertas
    ADD FOREIGN KEY (prm_producto_uu_id)
    REFERENCES public.prm_producto (uu_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_producto_prc_ofertas
    ADD FOREIGN KEY (prc_ofertas_id_producto)
    REFERENCES public.prc_ofertas (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_envios_prc_pedidos
    ADD FOREIGN KEY (prm_envios_id)
    REFERENCES public.prm_envios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.prm_envios_prc_pedidos
    ADD FOREIGN KEY (prc_pedidos_estado)
    REFERENCES public.prc_pedidos (estado) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;